[package]
name = "labrador-snark"
version = "0.1.0"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.13"
polynomial = "0.2.5"
nalgebra = "*"
