name: LaBRADOR Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
    - name: Set threads environment variable for Rayon
      run: echo "RAYON_NUM_THREADS=1" >> $GITHUB_ENV
    - name: Build and Run with a single thread
      run: |
        cargo build --verbose
        cargo run --release -- --ntt
